# cvat v2.6.1 docker compose configuration for devcontainer with docker in docker

services:
  cvat_db:
    restart: "no"
    init: true

  cvat_redis:
    restart: "no"
    init: true

  cvat_server:
    restart: "no"
    init: true
    labels:
      - traefik.http.routers.cvat.rule=(Host(`${CVAT_HOST:-localhost}`) &&
        PathPrefix(`/api/`, `/git/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`)) ||
        (Host(`127.0.0.1`) && PathPrefix(`/api/`, `/git/`, `/opencv/`, `/static/`, `/admin`, `/documentation/`, `/django-rq`))

  cvat_utils:
    restart: "no"
    init: true

  cvat_worker_import:
    restart: "no"
    init: true

  cvat_worker_export:
    restart: "no"
    init: true

  cvat_worker_annotation:
    restart: "no"
    init: true

  cvat_worker_webhooks:
    restart: "no"
    init: true

  cvat_worker_quality_reports:
    restart: "no"
    init: true

  cvat_worker_analytics_reports:
    restart: "no"
    init: true

  cvat_ui:
    restart: "no"
    init: true
    labels:
      - traefik.http.routers.cvat-ui.rule=Host(`${CVAT_HOST:-localhost}`) || Host(`127.0.0.1`)

  traefik:
    restart: "no"
    init: true
    ports: !reset []

  cvat_opa:
    restart: "no"
    init: true

  cvat_clickhouse:
    restart: "no"
    init: true

  cvat_vector:
    restart: "no"
    init: true

  cvat_grafana:
    restart: "no"
    init: true
